# Panic_Recover(异常捕获)

## Python

```python
try:
    raise Exception('Shit')
except Exception as e:
    print("error was:", e)
```

## Go

```go
package main

import "fmt"

func main() {
	// Running this will print out:
	//    error was: Shit!
	defer func() {
		fmt.Println("error was:",recover())			//error was: Shit!
	}()
	panic("Shit!")
}
```

